/* Automatisch erzeugt durch tools/generiere_daten.py – nicht von Hand bearbeiten.
 * Grundlage: XJustiz 3.6.2 (XSD) und offizielle Genericode-Codelisten. */
window.ENOVA_CODELISTEN = {
 "gds.anschriftstyp": {
  "name": "GDS.Anschriftstyp",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.anschriftstyp",
  "typ": 1,
  "standardVersion": "3.0",
  "versionen": {
   "3.0": [
    ["002", "Besucheranschrift"],
    ["003", "Dienst-/Geschäftsanschrift"],
    ["004", "Entlassungsanschrift"],
    ["005", "Ladungsanschrift"],
    ["006", "Tatortanschrift"],
    ["007", "Urlaubsanschrift"],
    ["008", "Verfahrens-/Zustellanschrift"],
    ["009", "Zweitwohnsitz"],
    ["010", "Sonstige"],
    ["011", "ohne festen Wohnsitz"],
    ["012", "unbekannter Aufenthalt"],
    ["013", "Großempfänger-Postfach"],
    ["014", "Postfach"],
    ["017", "Privatanschrift"],
    ["018", "Rechnungsanschrift"],
    ["019", "Vollzugsanschrift"],
    ["020", "Gerichtsfachanschrift"],
    ["021", "Lage der Geschäftsräume"]
   ]
  },
  "vollstaendig": true,
  "quelle": "XJustiz 3.6.2, xjustiz_0010_cl_allgemein_3_7.xsd"
 },
 "gds.telekommunikationsart": {
  "name": "GDS.Telekommunikationsart",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.telekommunikationsart",
  "typ": 1,
  "standardVersion": "2.3",
  "versionen": {
   "2.3": [
    ["001", "E-Mail"],
    ["002", "Fax"],
    ["003", "Internet"],
    ["004", "Mobiltelefon"],
    ["005", "Pager"],
    ["006", "Sonstige"],
    ["007", "Telefon"],
    ["008", "Rechtsverbindlicher elektronischer Kommunikationsweg"]
   ]
  },
  "vollstaendig": true,
  "quelle": "XJustiz 3.6.2, xjustiz_0060_cl_telekommunikation_3_1.xsd"
 },
 "gds.geschlecht": {
  "name": "GDS.Geschlecht",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.geschlecht",
  "typ": 1,
  "standardVersion": "2.1",
  "versionen": {
   "2.1": [
    ["0", "unbekannt"],
    ["1", "männlich"],
    ["2", "weiblich"],
    ["3", "divers"],
    ["4", "sächlich"]
   ]
  },
  "vollstaendig": true,
  "quelle": "XJustiz 3.6.2, xjustiz_0010_cl_allgemein_3_7.xsd"
 },
 "gds.familienstand": {
  "name": "GDS.Familienstand",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.familienstand",
  "typ": 1,
  "standardVersion": "2.0",
  "versionen": {
   "2.0": [
    ["001", "geschieden oder Ehe aufgehoben"],
    ["002", "getrennt lebend"],
    ["003", "Lebenspartnerschaft"],
    ["004", "Lebenspartnerschaft aufgehoben"],
    ["005", "Lebenspartner verstorben"],
    ["006", "Lebenspartner getrennt lebend"],
    ["007", "ledig"],
    ["008", "unbekannt"],
    ["009", "verheiratet"],
    ["010", "verwitwet"]
   ]
  },
  "vollstaendig": true,
  "quelle": "XJustiz 3.6.2, xjustiz_0010_cl_allgemein_3_7.xsd"
 },
 "gds.bestandteiltyp": {
  "name": "GDS.Bestandteiltyp",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.bestandteiltyp",
  "typ": 1,
  "standardVersion": "2.5",
  "versionen": {
   "2.5": [
    ["001", "Original"],
    ["002", "Repräsentat"],
    ["003", "Signaturdatei"],
    ["004", "signierte Vorversion"],
    ["006", "Transfervermerk"],
    ["010", "Prüfvermerk"],
    ["011", "VHN"],
    ["012", "hinlaufendes eEB"],
    ["013", "Datei im ursprünglichen Format"]
   ]
  },
  "vollstaendig": true,
  "quelle": "XJustiz 3.6.2, xjustiz_0010_cl_allgemein_3_7.xsd"
 },
 "dabag.wirtschaftsart": {
  "name": "DABAG.Wirtschaftsart",
  "uri": "urn:xoev-de:xjustiz:codeliste:dabag.wirtschaftsart",
  "typ": 1,
  "standardVersion": "1.0",
  "versionen": {
   "1.0": [
    ["001", "Erholungsfläche"],
    ["002", "Friedhof"],
    ["003", "Gebäude- und Freifläche Land- und Forstwirtschaft"],
    ["004", "Industrie- und Gewerbefläche"],
    ["005", "Landwirtschaftsfläche"],
    ["006", "Mischnutzung"],
    ["007", "Sonstige Vegetationsfläche"],
    ["008", "Unland"],
    ["009", "Verkehrsfläche"],
    ["010", "Waldfläche"],
    ["011", "Wasserfläche"],
    ["012", "Wohnbaufläche"]
   ]
  },
  "vollstaendig": true,
  "quelle": "XJustiz 3.6.2, xjustiz_2910_cl_dabag_3_1.xsd"
 },
 "dabag.grundbuchart": {
  "name": "DABAG.Grundbuchart",
  "uri": "urn:xoev-de:xjustiz:codeliste:dabag.grundbuchart",
  "typ": 1,
  "standardVersion": "1.0",
  "versionen": {
   "1.0": [
    ["001", "Altrechtliche Gemeinschaft"],
    ["002", "Altrechtliche Genossenschaften (Art. 164 EGBGB)"],
    ["003", "Anteilsgrundbuch"],
    ["004", "Apothekengerechtigkeit"],
    ["005", "Berggrundbuch"],
    ["006", "Bergkellergrundbuch"],
    ["007", "Denkmalschutz"],
    ["008", "Erbbaugrundbuch"],
    ["009", "Grundstücksgrundbuch"],
    ["010", "Gebäudegrundbuch"],
    ["011", "Gemeinderecht"],
    ["012", "Gemeinschaftsgrundbuch"],
    ["013", "Fischereigrundbuch"],
    ["014", "Nutzungsrecht"],
    ["015", "Realgewerbeberechtigung"],
    ["016", "Salzgrundbuch"],
    ["017", "Stavengrundbuch"],
    ["018", "Stockwerkseigentum"],
    ["019", "Superficiesgrundbuch"],
    ["020", "Teileigentumsgrundbuch"],
    ["021", "Teilgebäudegrundbuch"],
    ["022", "Teilerbbaugrundbuch"],
    ["023", "Teiluntererbbaugrundbuch"],
    ["024", "Untererbbaugrundbuch"],
    ["025", "Wohnungs- und Teileigentumsgrundbuch"],
    ["026", "Wohnungs- und Teilerbbaugrundbuch"],
    ["027", "Wohnungs- und Teilgebäudegrundbuch"],
    ["028", "Wohnungs- und Teiluntererbbaugrundbuch"],
    ["029", "Wohnungsgebäudegrundbuch"],
    ["030", "Wohnungsgrundbuch"],
    ["031", "Wohnungserbbaugrundbuch"],
    ["032", "Wohnungsuntererbbaugrundbuch"],
    ["033", "Zubehörgrundstück"]
   ]
  },
  "vollstaendig": true,
  "quelle": "XJustiz 3.6.2, xjustiz_2910_cl_dabag_3_1.xsd"
 },
 "dabag.aufteilungsgrund.weg": {
  "name": "DABAG.Aufteilungsgrund.WEG",
  "uri": "urn:xoev-de:xjustiz:codeliste:dabag.aufteilungsgrund.weg",
  "typ": 1,
  "standardVersion": "1.0",
  "versionen": {
   "1.0": [
    ["001", "Teilung nach § 3 WEG"],
    ["002", "Teilung nach § 8 WEG"]
   ]
  },
  "vollstaendig": true,
  "quelle": "XJustiz 3.6.2, xjustiz_2910_cl_dabag_3_1.xsd"
 },
 "gds.rollenbezeichnung": {
  "name": "GDS.Rollenbezeichnung",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.rollenbezeichnung",
  "typ": 3,
  "standardVersion": "3.5",
  "versionen": {
   "3.5": [
    ["001", "Abwesenheitspfleger(in)"],
    ["002", "Aliasidentität"],
    ["003", "Angehörige(r)"],
    ["004", "Angeklagte(r)"],
    ["005", "Angeschuldigte(r)"],
    ["006", "Annehmende(r)"],
    ["007", "Anschlussberufungsbeklagte(r)"],
    ["008", "Anschlussberufungskläger(in)"],
    ["009", "Anschlussbeschwerdeführer(in)"],
    ["010", "Anschlussbeschwerdegegner(in)"],
    ["011", "Anschlussrechtsbeschwerdeführer(in)"],
    ["012", "Anschlussrechtsbeschwerdegegner(in)"],
    ["013", "Anschlussrevisionsbeklagte(r)"],
    ["014", "Anschlussrevisionskläger(in)"],
    ["015", "Antragsgegner(in)"],
    ["016", "Antragsteller(in)"],
    ["017", "Anzeigeerstatter(in)"],
    ["018", "Anzunehmende(r)"],
    ["019", "Arrestgläubiger(in)"],
    ["020", "Arrestschuldner(in)"],
    ["021", "Aufsichtsbehörde"],
    ["022", "Ausschlagende(r)"],
    ["023", "Beamter (Beamtin)"],
    ["024", "Behörde"],
    ["025", "Beigeladene(r)"],
    ["026", "Beistand"],
    ["027", "Bekannte(r)"],
    ["028", "Beklagte(r)"],
    ["029", "Berufungsbeklagte(r)"],
    ["030", "Berufungskläger(in)"],
    ["031", "Beschuldigte(r)"],
    ["032", "Beschwerdeführer(in)"],
    ["033", "Beschwerdegegner(in)"],
    ["034", "Besucher(in)"],
    ["036", "Betreibende(r) Gläubige(r)"],
    ["037", "Betreuer(in)"],
    ["038", "Betreute(r)"],
    ["039", "Betreuungsbehörde"],
    ["040", "Betroffene(r)"],
    ["041", "Bevollmächtigte(r)"],
    ["042", "Bewährungshelfer(in)"],
    ["043", "Beweisanwalt (-anwältin)"],
    ["044", "Bruder (Schwester)"],
    ["045", "Bundeswehrdisziplinaranwalt (-anwältin)"],
    ["046", "Bußgeldempfänger(in)"],
    ["047", "Cousin(e)"],
    ["048", "Dienstvorgesetzte(r)"],
    ["049", "director"],
    ["050", "Dolmetscher(in)"],
    ["051", "Dritte(r)"],
    ["052", "Drittschuldner(in)"],
    ["053", "Drittwiderbeklagte(r)"],
    ["054", "Drittwiderkläger(in)"],
    ["056", "Ehemann (Ehefrau)"],
    ["057", "Eigentümer(in)"],
    ["058", "Eingetragene(r) Lebenspartner(in)"],
    ["059", "Einleitungsbehörde"],
    ["060", "Eltern"],
    ["061", "Elternteil"],
    ["062", "Enkel(in)"],
    ["063", "Erbe (Erbin)"],
    ["064", "Erbe (Erbin) (ausschlagend)"],
    ["065", "Erbe (Erbin) (vorverstorben)"],
    ["066", "Erblasser(in)"],
    ["067", "Ergänzungspfleger(in)"],
    ["068", "Erinnerungsführer(in)"],
    ["069", "Erinnerungsgegner(in)"],
    ["070", "Ersatzbetreuer(in)"],
    ["071", "Ersteher(in)"],
    ["072", "Erwerber(in)"],
    ["073", "Erziehungsberechtigte(r)"],
    ["074", "Frühere(r) Ehegatte (Ehegattin)"],
    ["075", "Frühere(r) Beklagte(r)"],
    ["076", "Frühere(r) Beteiligte(r)"],
    ["077", "Frühere(r) Gläubiger(in)"],
    ["078", "Frühere(r) Kläger(in)"],
    ["079", "Frühere(r) Soldat(in)"],
    ["080", "Gegenvormund"],
    ["081", "Generalbundesanwalt (-anwältin)"],
    ["082", "Gericht"],
    ["083", "Gerichtsvollzieher(in)"],
    ["084", "Geschädigte(r)"],
    ["085", "Geschäftsführende(r) Gesellschafter(in)"],
    ["086", "Geschäftsführer(in)"],
    ["087", "Gesetzliche(r) Erbe (Erbin)"],
    ["088", "Gesetzliche(r) Vertreter(in)"],
    ["089", "Gläubiger(in)"],
    ["090", "Großeltern"],
    ["092", "Großvater (Großmutter)"],
    ["093", "Hauptbevollmächtigte(r)"],
    ["094", "Hoferbe (Hoferbin)"],
    ["095", "Inhaber(in) der Firma"],
    ["096", "Insolvenzverwalter(in)"],
    ["097", "Jugendamt"],
    ["098", "Kammer"],
    ["099", "Kammermitglied"],
    ["100", "Kind"],
    ["101", "Kläger(in)"],
    ["102", "Kontrollbetreuer(in)"],
    ["103", "Korrespondenzanwalt (-anwältin)"],
    ["104", "Kostenschuldner(in)"],
    ["105", "Landwirtschaftsrichter(in)"],
    ["106", "Lebenspartner(in)"],
    ["107", "Liquidator(in)"],
    ["108", "Minderjährige(r)"],
    ["109", "Mitvormund"],
    ["110", "Mündel"],
    ["112", "Nachbesserungsgläubiger(in)"],
    ["113", "Nachlasspfleger(in)"],
    ["114", "Nachlassverwalter(in)"],
    ["115", "Nebenkläger(in)"],
    ["116", "Neffe (Nichte)"],
    ["117", "Nicht verwandt"],
    ["118", "Onkel (Tante)"],
    ["119", "Opfer"],
    ["120", "Pächter(in)"],
    ["121", "Pflegeeltern"],
    ["123", "Pfleger(in)"],
    ["124", "Pfleger(in) für das Sammelvermögen"],
    ["125", "Pfleger(in) für die Leibesfrucht"],
    ["126", "Pflegevater (Pflegemutter) des Mündels"],
    ["127", "Pflegling"],
    ["128", "Pflichtverteidiger(in)"],
    ["129", "Polizei"],
    ["130", "Privatbeklagte(r)"],
    ["131", "Privatkläger(in)"],
    ["132", "Prozessbevollmächtigte(r)"],
    ["133", "Prozesskostenhilfe-Anwalt (-Anwältin)"],
    ["134", "Prozesskostenhilfe-Korrespondenzanwalt (-anwältin)"],
    ["135", "Rechtsanwalt (-anwältin)"],
    ["136", "Rechtsbeistand"],
    ["137", "Rechtsbeschwerdeführer(in)"],
    ["138", "Rechtsbeschwerdegegner(in)"],
    ["139", "Revisionsbeklagte(r)"],
    ["140", "Revisionskläger(in)"],
    ["141", "Sachbearbeiter(in)"],
    ["142", "Sachverständige(r)"],
    ["143", "Schuldner(in)"],
    ["144", "Schwager (Schwägerin)"],
    ["146", "Schwiegersohn (Schwiegertochter)"],
    ["148", "Schwiegervater (Schwiegermutter)"],
    ["149", "Sohn (Tochter)"],
    ["150", "Soldat(in)"],
    ["151", "Sonstige(r) Beteiligte(r)"],
    ["152", "Sonstige(r) Vertreter(in)"],
    ["153", "Staatsanwaltschaft"],
    ["154", "Stiefeltern"],
    ["156", "Stiefvater (Stiefmutter)"],
    ["161", "Terminsbevollmächtigte(r)"],
    ["162", "Testamentsvollstrecker(in)"],
    ["163", "Testator(in)"],
    ["164", "Übernehmer(in)"],
    ["165", "Unterbevollmächtigte(r)"],
    ["166", "Ur-Enkel(in)"],
    ["167", "Vater (Mutter)"],
    ["168", "Veräußerer (Veräußerin)"],
    ["169", "Verfahrensbevollmächtigte(r)"],
    ["170", "Verfahrenskostenhilfe-Anwalt(-Anwältin)"],
    ["171", "Verfahrenskostenhilfe-Korrespondenzanwalt (-anwältin)"],
    ["172", "Verfahrenspfleger(in)"],
    ["173", "Verfahrensvertreter(in) (§787 ZPO)"],
    ["174", "Verfügungsbeklagte(r)"],
    ["175", "Verfügungskläger(in)"],
    ["176", "Verkehrsanwalt (-anwältin)"],
    ["177", "Verlobte(r)"],
    ["178", "Vermächtnisnehmer(in)"],
    ["179", "Vermieter(in)"],
    ["180", "Verpächter(in)"],
    ["181", "Versorgungsträger(in)"],
    ["182", "Verteidiger(in)"],
    ["183", "Vertreter(in) der Interessen des Ausgleichsfonds"],
    ["184", "Vertreter(in) der Staatskasse"],
    ["185", "Vertreter(in) des Bundesinteresses beim Bundesverwaltungsgericht"],
    ["186", "Vertreter(in) des öffentlichen Interesses"],
    ["187", "Verurteilte(r)"],
    ["188", "Verwalter(in) der Wohnungseigentümergemeinschaft"],
    ["189", "Verwaltungsbehörde"],
    ["190", "Vollstreckungsgläubiger(in)"],
    ["191", "Vollstreckungsschuldner(in)"],
    ["192", "Vorläufige(r) Betreuer(in)"],
    ["193", "Vormund"],
    ["194", "Vorstand"],
    ["195", "Vorsorgebevollmächtigte(r)"],
    ["196", "Wahlverteidiger(in)"],
    ["197", "Widerbeklagte(r)"],
    ["198", "Widerkläger(in)"],
    ["199", "Wiederaufnahmebeklagte(r)"],
    ["200", "Wiederaufnahmekläger(in)"],
    ["201", "Zahlungs- und Auflagenempfänger(in)"],
    ["202", "Zeuge (Zeugin)"],
    ["203", "Zeugenbeistand"],
    ["204", "Zulassungsantragsgegner(in)"],
    ["205", "Zulassungsantragsteller(in)"],
    ["206", "Zustellungsbevollmächtigte(r)"],
    ["207", "Zustellungsvertreter(in) (§6 ZVG)"],
    ["208", "Notar(in)"],
    ["209", "Auskunftsempfänger(in)"],
    ["210", "Melder(in)"],
    ["211", "Verwahrstelle"],
    ["212", "Aussteller(in)"],
    ["213", "Berechtigte(r)"],
    ["214", "Berechtigte(r) an einem Recht"],
    ["215", "Einreicher(in)"],
    ["216", "Erbbauberechtigte(r)"],
    ["217", "Finanzamt"],
    ["218", "Grundbuchvertreter(in)"],
    ["219", "Insolvenzgericht"],
    ["220", "Mitteilungsempfänger(in)"],
    ["221", "Nacherbe (Nacherbin)"],
    ["222", "Rechnungsempfänger(in)"],
    ["223", "Veranlasser(in)"],
    ["224", "Versteigerungsabteilung"],
    ["225", "Vertretungsberechtigte(r)"],
    ["226", "Zweitschuldner(in)"],
    ["227", "Vertreter(in)"],
    ["228", "Arbeitgeber(in)"],
    ["229", "RV-Träger(in)"],
    ["230", "Vollstreckungsstelle"],
    ["231", "Abkömmling"],
    ["232", "Kreditnehmer(in)"],
    ["233", "Neu vorzutragende(r) Eigentümer(in)"],
    ["234", "Notariatsverwalter(in)"],
    ["235", "Notarvertreter(in)"],
    ["236", "Partei kraft Amtes"],
    ["237", "Sequester"],
    ["238", "Treuhänder(in)"],
    ["239", "Zustimmende(r)"],
    ["240", "Gläubigervertreter(in)"],
    ["241", "Schuldnervertreter(in)"],
    ["242", "Zahlungsempfänger(in)"],
    ["243", "Anteilsinhaber(in)"],
    ["244", "Antragsteller(in) -Eröffnung"],
    ["245", "Debitor(in)"],
    ["246", "Gesellschafter(in)"],
    ["247", "Handlungsbevollmächtigte(r)"],
    ["248", "Mitglied einer Gesamt-Anteilsinhaberschaft"],
    ["249", "Mitglied einer Gläubigergemeinschaft"],
    ["250", "Mitreeder(in)"],
    ["251", "Partner(in)"],
    ["252", "Persönlich haftende(r) Gesellschafter(in)"],
    ["253", "Prozesspfleger(in)"],
    ["254", "Sachwalter(in)"],
    ["255", "Treuhänder(in) (Wohlverhaltensperiode)"],
    ["256", "Vermögensträger(in)"],
    ["257", "Vorläufige(r) Insolvenzverwalter(in)"],
    ["258", "Vorläufige(r) Treuhänder(in)"],
    ["259", "Sondersachwalter(in)"],
    ["260", "Sonderinsolvenzverwalter(in)"],
    ["261", "Vorläufige(r) Sachwalter(in)"],
    ["262", "Abwickler(in)"],
    ["263", "Übernehmender Rechtsträger"],
    ["264", "Aufsichtsrat (-rätin)"],
    ["265", "Besondere(r) Vertreter(in) nach § 30 BGB"],
    ["266", "Betriebsleiter(in)"],
    ["267", "Empfangsberechtigte(r)"],
    ["268", "Geschäftsführende(r) Direktor(in)"],
    ["269", "Geschäftsleiter(in)"],
    ["271", "Gründer(in)"],
    ["272", "Gründungsprüfer(in)"],
    ["273", "Hauptniederlassung"],
    ["274", "Inhaber(in)"],
    ["275", "Kommanditist(in)"],
    ["276", "Konkursverwalter(in)"],
    ["277", "Mitglied des Leitungsorgans"],
    ["278", "Mitglied EWIV"],
    ["279", "Nachgründungsprüfer(in)"],
    ["280", "Nachtragsabwickler(in)"],
    ["281", "Nachtragsliquidator(in)"],
    ["282", "Notgeschäftsführer(in)"],
    ["283", "Notliquidator(in)"],
    ["284", "Notvorstand"],
    ["285", "Prokurist(in)"],
    ["287", "Rechtsträger(in)"],
    ["288", "Registergericht"],
    ["289", "Sacheinlagenprüfer(in)"],
    ["290", "Ständige(r) Vertreter(in) für die Zweigniederlassung"],
    ["291", "Übertragender Rechtsträger"],
    ["292", "Vergleichsverwalter(in)"],
    ["293", "Verwaltungsrat (-rätin)"],
    ["294", "Vorstandsvorsitzende(r)"],
    ["295", "Zweigniederlassung"],
    ["296", "Vertreter(in) des Klägers/der Klägerin"],
    ["297", "Vertreter(in) des/der Beklagten"],
    ["298", "Bewährungshilfe"],
    ["299", "Gerichtshilfe"],
    ["300", "Justizvollzug"],
    ["301", "Pseudoname"],
    ["302", "Gesetzliche(r) Vertreter(in) des Gläubigers/der Gläubigerin"],
    ["303", "Gesetzliche(r) Vertreter(in) des Schuldners/der Schuldnerin"],
    ["304", "Bevollmächtigte(r) des Gläubigers/der Gläubigerin"],
    ["305", "Bevollmächtigte(r) des Schuldners/der Schuldnerin"],
    ["306", "Fahrzeughalter(in)"],
    ["307", "Frühere(r) Lebenspartner(in)"],
    ["308", "Sicherungsverwalter(in)"],
    ["309", "Zwangsverwalter(in)"],
    ["310", "Mieter(in)"],
    ["311", "Bürge (Bürgin)"],
    ["312", "Meistbietende(r)"],
    ["313", "Abschlussprüfer(in)"],
    ["314", "Antragstellervertreter(in)"],
    ["315", "Aufsichtsratsvorsitzende(r)"],
    ["316", "Berufskammer"],
    ["317", "Betroffenenvertreter(in)"],
    ["318", "Bürgermeister(in)"],
    ["319", "Eingliederungsbeteiligte(r)"],
    ["320", "Formwechselnder Rechtsträger"],
    ["321", "Gewerbeamt"],
    ["322", "Inhaber(in) (nicht eingetragen)"],
    ["323", "Kostenempfänger(in)"],
    ["324", "Nachlassgericht"],
    ["325", "Sonderprüfer(in)"],
    ["326", "Sonstige(r) gerichtlich bestellte(r) Vertreter(in)"],
    ["327", "Sonstige(r) gesetzliche(r) Vertreter(in) BGB"],
    ["328", "Sonstige(r) organschaftliche(r) Vertreter(in) HRB"],
    ["329", "Standardkostenschuldner(in)"],
    ["330", "Übernahmeschuldner(in)"],
    ["331", "Unternehmensvertragsbeteiligte(r)"],
    ["332", "Vertreter(in) des persönlich haftenden Gesellschafters"],
    ["333", "Werkleiter(in)"],
    ["334", "Mehrfachsitz"],
    ["335", "Mitglied VR"],
    ["336", "Mitglied e. BGB-Gesellschaft als Abwicklerin"],
    ["337", "Mitglied e. BGB-Gesellschaft als ges. Vertreterin"],
    ["338", "Mitglied e. BGB-Gesellschaft als Kommanditistin"],
    ["339", "Mitglied e. BGB-Gesellschaft als Liquidatorin"],
    ["340", "Mitglied e. BGB-Gesellschaft als Mitglied e. EWIV"],
    ["341", "Mitglied e. BGB-Gesellschaft als phG"],
    ["342", "Mitglied e. Erbengemeinschaft als ges. Vertreterin"],
    ["343", "Mitglied e. Erbengemeinschaft als Inhaberin"],
    ["344", "Mitglied e. Erbengemeinschaft als Kommanditistin"],
    ["345", "Mitglied e. Erbengemeinschaft als Mitglied e. EWIV"],
    ["346", "Nebensitz"],
    ["347", "Gesamthandsgemeinschaft"],
    ["348", "Mitglied einer Gesamthandsgemeinschaft"],
    ["349", "Leitungsperson i.S.v. § 30 Abs. 1 Nr. 1 bis 5 OWiG"],
    ["350", "Einziehungsbeteiligter"],
    ["351", "Antragsgegnervertreter(in)"],
    ["352", "Verbraucher(in)"],
    ["353", "Vielmelder(in)"],
    ["354", "Vollmachtgeber(in)"],
    ["355", "Nebenbeteiligte(r) § 444 StPO"],
    ["356", "Verfallsbeteiligte(r) § 442 StPO a.F."],
    ["357", "Verfolgte(r) § 34 IRG"],
    ["358", "Rechtsnachfolger(in)"],
    ["359", "Statuswechselnde(r) Rechtsträger(in)"],
    ["360", "Haftangehörige"],
    ["361", "Restrukturierungsbeauftragte(r)"],
    ["362", "Sanierungsmoderator(in)"],
    ["363", "Abschriftenempfänger(in)"],
    ["364", "Kostenbeamte(r)"],
    ["365", "Urkundsbeamte(r) der Geschäftsstelle"],
    ["366", "Anordnungsbefugte(r)"],
    ["367", "Erstschuldner(in)"],
    ["368", "Kasse"],
    ["369", "Arrestbeklagte(r)"],
    ["370", "Arrestkläger(in)"],
    ["371", "Bezirksrevisor(in)"],
    ["372", "Nebenintervenient(in)"],
    ["373", "Restitutionsbeklagte(r)"],
    ["374", "Restitutionskläger(in)"],
    ["375", "Streithelfer(in)"],
    ["376", "Streitverkündete(r)"],
    ["377", "Übersetzer(in)"]
   ],
   "3.6": [
    ["001", "Abwesenheitspfleger(in)"],
    ["002", "Aliasidentität"],
    ["003", "Angehörige(r)"],
    ["004", "Angeklagte(r)"],
    ["005", "Angeschuldigte(r)"],
    ["006", "Annehmende(r)"],
    ["007", "Anschlussberufungsbeklagte(r)"],
    ["008", "Anschlussberufungskläger(in)"],
    ["009", "Anschlussbeschwerdeführer(in)"],
    ["010", "Anschlussbeschwerdegegner(in)"],
    ["011", "Anschlussrechtsbeschwerdeführer(in)"],
    ["012", "Anschlussrechtsbeschwerdegegner(in)"],
    ["013", "Anschlussrevisionsbeklagte(r)"],
    ["014", "Anschlussrevisionskläger(in)"],
    ["015", "Antragsgegner(in)"],
    ["016", "Antragsteller(in)"],
    ["017", "Anzeigeerstatter(in)"],
    ["018", "Anzunehmende(r)"],
    ["019", "Arrestgläubiger(in)"],
    ["020", "Arrestschuldner(in)"],
    ["021", "Aufsichtsbehörde"],
    ["022", "Ausschlagende(r)"],
    ["023", "Beamter (Beamtin)"],
    ["024", "Behörde"],
    ["025", "Beigeladene(r)"],
    ["026", "Beistand"],
    ["027", "Bekannte(r)"],
    ["028", "Beklagte(r)"],
    ["029", "Berufungsbeklagte(r)"],
    ["030", "Berufungskläger(in)"],
    ["031", "Beschuldigte(r)"],
    ["032", "Beschwerdeführer(in)"],
    ["033", "Beschwerdegegner(in)"],
    ["034", "Besucher(in)"],
    ["036", "Betreibende(r) Gläubige(r)"],
    ["037", "Betreuer(in)"],
    ["038", "Betreute(r)"],
    ["039", "Betreuungsbehörde"],
    ["040", "Betroffene(r)"],
    ["041", "Bevollmächtigte(r)"],
    ["042", "Bewährungshelfer(in)"],
    ["043", "Beweisanwalt (-anwältin)"],
    ["044", "Bruder (Schwester)"],
    ["045", "Bundeswehrdisziplinaranwalt (-anwältin)"],
    ["046", "Bußgeldempfänger(in)"],
    ["047", "Cousin(e)"],
    ["048", "Dienstvorgesetzte(r)"],
    ["049", "director"],
    ["050", "Dolmetscher(in)"],
    ["051", "Dritte(r)"],
    ["052", "Drittschuldner(in)"],
    ["053", "Drittwiderbeklagte(r)"],
    ["054", "Drittwiderkläger(in)"],
    ["056", "Ehemann (Ehefrau)"],
    ["057", "Eigentümer(in)"],
    ["058", "Eingetragene(r) Lebenspartner(in)"],
    ["059", "Einleitungsbehörde"],
    ["060", "Eltern"],
    ["061", "Elternteil"],
    ["062", "Enkel(in)"],
    ["063", "Erbe (Erbin)"],
    ["064", "Erbe (Erbin) (ausschlagend)"],
    ["065", "Erbe (Erbin) (vorverstorben)"],
    ["066", "Erblasser(in)"],
    ["067", "Ergänzungspfleger(in)"],
    ["068", "Erinnerungsführer(in)"],
    ["069", "Erinnerungsgegner(in)"],
    ["070", "Ersatzbetreuer(in)"],
    ["071", "Ersteher(in)"],
    ["072", "Erwerber(in)"],
    ["073", "Erziehungsberechtigte(r)"],
    ["074", "Frühere(r) Ehegatte (Ehegattin)"],
    ["075", "Frühere(r) Beklagte(r)"],
    ["076", "Frühere(r) Beteiligte(r)"],
    ["077", "Frühere(r) Gläubiger(in)"],
    ["078", "Frühere(r) Kläger(in)"],
    ["079", "Frühere(r) Soldat(in)"],
    ["080", "Gegenvormund"],
    ["081", "Generalbundesanwalt (-anwältin)"],
    ["082", "Gericht"],
    ["083", "Gerichtsvollzieher(in)"],
    ["084", "Geschädigte(r)"],
    ["085", "Geschäftsführende(r) Gesellschafter(in)"],
    ["086", "Geschäftsführer(in)"],
    ["087", "Gesetzliche(r) Erbe (Erbin)"],
    ["088", "Gesetzliche(r) Vertreter(in)"],
    ["089", "Gläubiger(in)"],
    ["090", "Großeltern"],
    ["092", "Großvater (Großmutter)"],
    ["093", "Hauptbevollmächtigte(r)"],
    ["094", "Hoferbe (Hoferbin)"],
    ["095", "Inhaber(in) der Firma"],
    ["096", "Insolvenzverwalter(in)"],
    ["097", "Jugendamt"],
    ["098", "Kammer"],
    ["099", "Kammermitglied"],
    ["100", "Kind"],
    ["101", "Kläger(in)"],
    ["102", "Kontrollbetreuer(in)"],
    ["103", "Korrespondenzanwalt (-anwältin)"],
    ["104", "Kostenschuldner(in)"],
    ["105", "Landwirtschaftsrichter(in)"],
    ["106", "Lebenspartner(in)"],
    ["107", "Liquidator(in)"],
    ["108", "Minderjährige(r)"],
    ["109", "Mitvormund"],
    ["110", "Mündel"],
    ["112", "Nachbesserungsgläubiger(in)"],
    ["113", "Nachlasspfleger(in)"],
    ["114", "Nachlassverwalter(in)"],
    ["115", "Nebenkläger(in)"],
    ["116", "Neffe (Nichte)"],
    ["117", "Nicht verwandt"],
    ["118", "Onkel (Tante)"],
    ["119", "Opfer"],
    ["120", "Pächter(in)"],
    ["121", "Pflegeeltern"],
    ["123", "Pfleger(in)"],
    ["124", "Pfleger(in) für das Sammelvermögen"],
    ["125", "Pfleger(in) für die Leibesfrucht"],
    ["126", "Pflegevater (Pflegemutter) des Mündels"],
    ["127", "Pflegling"],
    ["128", "Pflichtverteidiger(in)"],
    ["129", "Polizei"],
    ["130", "Privatbeklagte(r)"],
    ["131", "Privatkläger(in)"],
    ["132", "Prozessbevollmächtigte(r)"],
    ["133", "Prozesskostenhilfe-Anwalt (-Anwältin)"],
    ["134", "Prozesskostenhilfe-Korrespondenzanwalt (-anwältin)"],
    ["135", "Rechtsanwalt (-anwältin)"],
    ["136", "Rechtsbeistand"],
    ["137", "Rechtsbeschwerdeführer(in)"],
    ["138", "Rechtsbeschwerdegegner(in)"],
    ["139", "Revisionsbeklagte(r)"],
    ["140", "Revisionskläger(in)"],
    ["141", "Sachbearbeiter(in)"],
    ["142", "Sachverständige(r)"],
    ["143", "Schuldner(in)"],
    ["144", "Schwager (Schwägerin)"],
    ["146", "Schwiegersohn (Schwiegertochter)"],
    ["148", "Schwiegervater (Schwiegermutter)"],
    ["149", "Sohn (Tochter)"],
    ["150", "Soldat(in)"],
    ["151", "Sonstige(r) Beteiligte(r)"],
    ["152", "Sonstige(r) Vertreter(in)"],
    ["153", "Staatsanwaltschaft"],
    ["154", "Stiefeltern"],
    ["156", "Stiefvater (Stiefmutter)"],
    ["161", "Terminsbevollmächtigte(r)"],
    ["162", "Testamentsvollstrecker(in)"],
    ["163", "Testator(in)"],
    ["164", "Übernehmer(in)"],
    ["165", "Unterbevollmächtigte(r)"],
    ["166", "Ur-Enkel(in)"],
    ["167", "Vater (Mutter)"],
    ["168", "Veräußerer (Veräußerin)"],
    ["169", "Verfahrensbevollmächtigte(r)"],
    ["170", "Verfahrenskostenhilfe-Anwalt(-Anwältin)"],
    ["171", "Verfahrenskostenhilfe-Korrespondenzanwalt (-anwältin)"],
    ["172", "Verfahrenspfleger(in)"],
    ["173", "Verfahrensvertreter(in) (§787 ZPO)"],
    ["174", "Verfügungsbeklagte(r)"],
    ["175", "Verfügungskläger(in)"],
    ["176", "Verkehrsanwalt (-anwältin)"],
    ["177", "Verlobte(r)"],
    ["178", "Vermächtnisnehmer(in)"],
    ["179", "Vermieter(in)"],
    ["180", "Verpächter(in)"],
    ["181", "Versorgungsträger(in)"],
    ["182", "Verteidiger(in)"],
    ["183", "Vertreter(in) der Interessen des Ausgleichsfonds"],
    ["184", "Vertreter(in) der Staatskasse"],
    ["185", "Vertreter(in) des Bundesinteresses beim Bundesverwaltungsgericht"],
    ["186", "Vertreter(in) des öffentlichen Interesses"],
    ["187", "Verurteilte(r)"],
    ["188", "Verwalter(in) der Wohnungseigentümergemeinschaft"],
    ["189", "Verwaltungsbehörde"],
    ["190", "Vollstreckungsgläubiger(in)"],
    ["191", "Vollstreckungsschuldner(in)"],
    ["192", "Vorläufige(r) Betreuer(in)"],
    ["193", "Vormund"],
    ["194", "Vorstand"],
    ["195", "Vorsorgebevollmächtigte(r)"],
    ["196", "Wahlverteidiger(in)"],
    ["197", "Widerbeklagte(r)"],
    ["198", "Widerkläger(in)"],
    ["199", "Wiederaufnahmebeklagte(r)"],
    ["200", "Wiederaufnahmekläger(in)"],
    ["201", "Zahlungs- und Auflagenempfänger(in)"],
    ["202", "Zeuge (Zeugin)"],
    ["203", "Zeugenbeistand"],
    ["204", "Zulassungsantragsgegner(in)"],
    ["205", "Zulassungsantragsteller(in)"],
    ["206", "Zustellungsbevollmächtigte(r)"],
    ["207", "Zustellungsvertreter(in) (§6 ZVG)"],
    ["208", "Notar(in)"],
    ["209", "Auskunftsempfänger(in)"],
    ["210", "Melder(in)"],
    ["211", "Verwahrstelle"],
    ["212", "Aussteller(in)"],
    ["213", "Berechtigte(r)"],
    ["214", "Berechtigte(r) an einem Recht"],
    ["215", "Einreicher(in)"],
    ["216", "Erbbauberechtigte(r)"],
    ["217", "Finanzamt"],
    ["218", "Grundbuchvertreter(in)"],
    ["219", "Insolvenzgericht"],
    ["220", "Mitteilungsempfänger(in)"],
    ["221", "Nacherbe (Nacherbin)"],
    ["222", "Rechnungsempfänger(in)"],
    ["223", "Veranlasser(in)"],
    ["224", "Versteigerungsabteilung"],
    ["225", "Vertretungsberechtigte(r)"],
    ["226", "Zweitschuldner(in)"],
    ["227", "Vertreter(in)"],
    ["228", "Arbeitgeber(in)"],
    ["229", "RV-Träger(in)"],
    ["230", "Vollstreckungsstelle"],
    ["231", "Abkömmling"],
    ["232", "Kreditnehmer(in)"],
    ["233", "Neu vorzutragende(r) Eigentümer(in)"],
    ["234", "Notariatsverwalter(in)"],
    ["235", "Notarvertreter(in)"],
    ["236", "Partei kraft Amtes"],
    ["237", "Sequester"],
    ["238", "Treuhänder(in)"],
    ["239", "Zustimmende(r)"],
    ["240", "Gläubigervertreter(in)"],
    ["241", "Schuldnervertreter(in)"],
    ["242", "Zahlungsempfänger(in)"],
    ["243", "Anteilsinhaber(in)"],
    ["244", "Antragsteller(in) -Eröffnung"],
    ["245", "Debitor(in)"],
    ["246", "Gesellschafter(in)"],
    ["247", "Handlungsbevollmächtigte(r)"],
    ["248", "Mitglied einer Gesamt-Anteilsinhaberschaft"],
    ["249", "Mitglied einer Gläubigergemeinschaft"],
    ["250", "Mitreeder(in)"],
    ["251", "Partner(in)"],
    ["252", "Persönlich haftende(r) Gesellschafter(in)"],
    ["253", "Prozesspfleger(in)"],
    ["254", "Sachwalter(in)"],
    ["255", "Treuhänder(in) (Wohlverhaltensperiode)"],
    ["256", "Vermögensträger(in)"],
    ["257", "Vorläufige(r) Insolvenzverwalter(in)"],
    ["258", "Vorläufige(r) Treuhänder(in)"],
    ["259", "Sondersachwalter(in)"],
    ["260", "Sonderinsolvenzverwalter(in)"],
    ["261", "Vorläufige(r) Sachwalter(in)"],
    ["262", "Abwickler(in)"],
    ["263", "Übernehmender Rechtsträger"],
    ["264", "Aufsichtsrat (-rätin)"],
    ["265", "Besondere(r) Vertreter(in) nach § 30 BGB"],
    ["266", "Betriebsleiter(in)"],
    ["267", "Empfangsberechtigte(r)"],
    ["268", "Geschäftsführende(r) Direktor(in)"],
    ["269", "Geschäftsleiter(in)"],
    ["271", "Gründer(in)"],
    ["272", "Gründungsprüfer(in)"],
    ["273", "Hauptniederlassung"],
    ["274", "Inhaber(in)"],
    ["275", "Kommanditist(in)"],
    ["276", "Konkursverwalter(in)"],
    ["277", "Mitglied des Leitungsorgans"],
    ["278", "Mitglied EWIV"],
    ["279", "Nachgründungsprüfer(in)"],
    ["280", "Nachtragsabwickler(in)"],
    ["281", "Nachtragsliquidator(in)"],
    ["282", "Notgeschäftsführer(in)"],
    ["283", "Notliquidator(in)"],
    ["284", "Notvorstand"],
    ["285", "Prokurist(in)"],
    ["287", "Rechtsträger(in)"],
    ["288", "Registergericht"],
    ["289", "Sacheinlagenprüfer(in)"],
    ["290", "Ständige(r) Vertreter(in) für die Zweigniederlassung"],
    ["291", "Übertragender Rechtsträger"],
    ["292", "Vergleichsverwalter(in)"],
    ["293", "Verwaltungsrat (-rätin)"],
    ["294", "Vorstandsvorsitzende(r)"],
    ["295", "Zweigniederlassung"],
    ["296", "Vertreter(in) des Klägers/der Klägerin"],
    ["297", "Vertreter(in) des/der Beklagten"],
    ["298", "Bewährungshilfe"],
    ["299", "Gerichtshilfe"],
    ["300", "Justizvollzug"],
    ["301", "Pseudoname"],
    ["302", "Gesetzliche(r) Vertreter(in) des Gläubigers/der Gläubigerin"],
    ["303", "Gesetzliche(r) Vertreter(in) des Schuldners/der Schuldnerin"],
    ["304", "Bevollmächtigte(r) des Gläubigers/der Gläubigerin"],
    ["305", "Bevollmächtigte(r) des Schuldners/der Schuldnerin"],
    ["306", "Fahrzeughalter(in)"],
    ["307", "Frühere(r) Lebenspartner(in)"],
    ["308", "Sicherungsverwalter(in)"],
    ["309", "Zwangsverwalter(in)"],
    ["310", "Mieter(in)"],
    ["311", "Bürge (Bürgin)"],
    ["312", "Meistbietende(r)"],
    ["313", "Abschlussprüfer(in)"],
    ["314", "Antragstellervertreter(in)"],
    ["315", "Aufsichtsratsvorsitzende(r)"],
    ["316", "Berufskammer"],
    ["317", "Betroffenenvertreter(in)"],
    ["318", "Bürgermeister(in)"],
    ["319", "Eingliederungsbeteiligte(r)"],
    ["320", "Formwechselnder Rechtsträger"],
    ["321", "Gewerbeamt"],
    ["322", "Inhaber(in) (nicht eingetragen)"],
    ["323", "Kostenempfänger(in)"],
    ["324", "Nachlassgericht"],
    ["325", "Sonderprüfer(in)"],
    ["326", "Sonstige(r) gerichtlich bestellte(r) Vertreter(in)"],
    ["327", "Sonstige(r) gesetzliche(r) Vertreter(in) BGB"],
    ["328", "Sonstige(r) organschaftliche(r) Vertreter(in) HRB"],
    ["329", "Standardkostenschuldner(in)"],
    ["330", "Übernahmeschuldner(in)"],
    ["331", "Unternehmensvertragsbeteiligte(r)"],
    ["332", "Vertreter(in) des persönlich haftenden Gesellschafters"],
    ["333", "Werkleiter(in)"],
    ["334", "Mehrfachsitz"],
    ["335", "Mitglied VR"],
    ["336", "Mitglied e. BGB-Gesellschaft als Abwicklerin"],
    ["337", "Mitglied e. BGB-Gesellschaft als ges. Vertreterin"],
    ["338", "Mitglied e. BGB-Gesellschaft als Kommanditistin"],
    ["339", "Mitglied e. BGB-Gesellschaft als Liquidatorin"],
    ["340", "Mitglied e. BGB-Gesellschaft als Mitglied e. EWIV"],
    ["341", "Mitglied e. BGB-Gesellschaft als phG"],
    ["342", "Mitglied e. Erbengemeinschaft als ges. Vertreterin"],
    ["343", "Mitglied e. Erbengemeinschaft als Inhaberin"],
    ["344", "Mitglied e. Erbengemeinschaft als Kommanditistin"],
    ["345", "Mitglied e. Erbengemeinschaft als Mitglied e. EWIV"],
    ["346", "Nebensitz"],
    ["347", "Gesamthandsgemeinschaft"],
    ["348", "Mitglied einer Gesamthandsgemeinschaft"],
    ["349", "Leitungsperson i.S.v. § 30 Abs. 1 Nr. 1 bis 5 OWiG"],
    ["350", "Einziehungsbeteiligter"],
    ["351", "Antragsgegnervertreter(in)"],
    ["352", "Verbraucher(in)"],
    ["353", "Vielmelder(in)"],
    ["354", "Vollmachtgeber(in)"],
    ["355", "Nebenbeteiligte(r) § 444 StPO"],
    ["356", "Verfallsbeteiligte(r) § 442 StPO a.F."],
    ["357", "Verfolgte(r) § 34 IRG"],
    ["358", "Rechtsnachfolger(in)"],
    ["359", "Statuswechselnde(r) Rechtsträger(in)"],
    ["360", "Haftangehörige"],
    ["361", "Restrukturierungsbeauftragte(r)"],
    ["362", "Sanierungsmoderator(in)"],
    ["363", "Abschriftenempfänger(in)"],
    ["364", "Kostenbeamte(r)"],
    ["365", "Urkundsbeamte(r) der Geschäftsstelle"],
    ["366", "Anordnungsbefugte(r)"],
    ["367", "Erstschuldner(in)"],
    ["368", "Kasse"],
    ["369", "Arrestbeklagte(r)"],
    ["370", "Arrestkläger(in)"],
    ["371", "Bezirksrevisor(in)"],
    ["372", "Nebenintervenient(in)"],
    ["373", "Restitutionsbeklagte(r)"],
    ["374", "Restitutionskläger(in)"],
    ["375", "Streithelfer(in)"],
    ["376", "Streitverkündete(r)"],
    ["377", "Übersetzer(in)"],
    ["378", "Unternehmen"],
    ["379", "Kontaktperson des Unternehmens"],
    ["380", "Beigetretene(r)"],
    ["381", "Erklärende(r)"],
    ["382", "Heim"],
    ["383", "Inhaftierte Person"],
    ["384", "Jugendgerichtshilfe"],
    ["385", "Krankenhaus"],
    ["386", "Nebenbetroffene(r)"],
    ["387", "Nebenklägervertreter(in)"],
    ["388", "Psychosoziale(r) Prozessbegleiter(in)"],
    ["389", "Rentenberater(in)"],
    ["390", "Sachverständige(n) Zeuge (Zeugin)"],
    ["391", "Steuerberater(in)"],
    ["392", "Unternehmen"],
    ["393", "Verfahrensbeistand"],
    ["394", "Verfahrensbeteiligte(r)"],
    ["395", "Verhinderungsbetreuer"],
    ["396", "Verletztenbeistand"],
    ["397", "Wirtschaftsprüfer(in)"],
    ["398", "Zedent(in)"],
    ["399", "Registerführende Behörde/Stelle"]
   ]
  },
  "vollstaendig": true,
  "quelle": "Genericode (XRepository): GDS.Rollenbezeichnung-3.5.xml, GDS.Rollenbezeichnung-3.6.xml"
 },
 "enova.ersuchensachentscheidung": {
  "name": "ENOVA.ErsuchenSachentscheidung",
  "uri": "urn:xoev-de:xjustiz:codeliste:enova.ersuchensachentscheidung",
  "typ": 3,
  "standardVersion": "1.0",
  "versionen": {
   "1.0": [
    ["001", "Mitteilung, ob der Grundbesitz von einem gesetzlichen Vorkaufsrecht der Gemeinde betroffen ist"],
    ["002", "Mitteilung, ob auf die Ausübung des/der gesetzlichen Vorkaufsrechts/-e der Gemeinde an dem Grundbesitz verzichtet wird"],
    ["003", "Mitteilung, ob der Grundbesitz von einem gesetzlichen Vorkaufsrecht der Gemeinde betroffen ist und, falls ja, ob auf die Ausübung des/der gesetzlichen Vorkaufsrechts/-e der Gemeinde verzichtet wird"],
    ["004", "Erteilung der sanierungsrechtlichen Genehmigung gemäß §§ 144, 145 BauGB"],
    ["005", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im städtebaulichen Entwicklungsbereich gemäß § 169 Abs. 1 Nr. 3 i.V.m. §§ 144, 145 BauGB"],
    ["006", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im Gebiet mit Fremdenverkehrsfunktion gemäß § 22 BauGB"],
    ["007", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im Bereich einer Erhaltungssatzung gemäß §§ 172, 173 BauGB"],
    ["008", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im Umlegungsgebiet gemäß § 51 BauGB"],
    ["009", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge bei eingeleitetem Enteignungsverfahren gemäß §§ 108, 109 BauGB"],
    ["010", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im Gebiet mit angespannten Wohnungsmärkten gemäß § 250 BauGB"],
    ["011", "Erteilung der Genehmigung nach § 2 GrdstVG"],
    ["012", "Erteilung der Genehmigung nach § 2 GVO"],
    ["013", "Erteilung der familiengerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte und hilfsweise um Erteilung eines Negativattests"],
    ["014", "Erteilung der betreuungsgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte und hilfsweise um Erteilung eines Negativattests"],
    ["015", "Erteilung der nachlassgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte und hilfsweise um Erteilung eines Negativattests"],
    ["016", "Erteilung eines Rechtskraftzeugnisses gemäß § 46 FamFG"],
    ["017", "Bitte um Erteilung der Unbedenklichkeitsentscheidung"]
   ],
   "1.1": [
    ["001", "Mitteilung, ob der Grundbesitz von einem gesetzlichen Vorkaufsrecht der Gemeinde betroffen ist"],
    ["002", "Mitteilung, ob auf die Ausübung des/der gesetzlichen Vorkaufsrechts/-e der Gemeinde an dem Grundbesitz verzichtet wird"],
    ["003", "Mitteilung, ob der Grundbesitz von einem gesetzlichen Vorkaufsrecht der Gemeinde betroffen ist und, falls ja, ob auf die Ausübung des/der gesetzlichen Vorkaufsrechts/-e der Gemeinde verzichtet wird"],
    ["004", "Erteilung der sanierungsrechtlichen Genehmigung gemäß §§ 144, 145 BauGB"],
    ["005", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im städtebaulichen Entwicklungsbereich gemäß § 169 Abs. 1 Nr. 3 i.V.m. §§ 144, 145 BauGB"],
    ["006", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im Gebiet mit Fremdenverkehrsfunktion gemäß § 22 BauGB"],
    ["007", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im Bereich einer Erhaltungssatzung gemäß §§ 172, 173 BauGB"],
    ["008", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im Umlegungsgebiet gemäß § 51 BauGB"],
    ["009", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge bei eingeleitetem Enteignungsverfahren gemäß §§ 108, 109 BauGB"],
    ["010", "Erteilung der Genehmigung für Vorhaben und Rechtsvorgänge im Gebiet mit angespannten Wohnungsmärkten gemäß § 250 BauGB"],
    ["011", "Erteilung der Genehmigung nach § 2 GrdstVG"],
    ["012", "Erteilung der Genehmigung nach § 2 GVO"],
    ["013", "Erteilung der familiengerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte und hilfsweise um Erteilung eines Negativattests"],
    ["014", "Erteilung der betreuungsgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte und hilfsweise um Erteilung eines Negativattests"],
    ["015", "Erteilung der nachlassgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte und hilfsweise um Erteilung eines Negativattests"],
    ["016", "Erteilung eines Rechtskraftzeugnisses gemäß § 46 FamFG"],
    ["017", "Bitte um Erteilung der Unbedenklichkeitsbescheinigung gemäß § 22 GrEStG"],
    ["018", "Erteilung des Zeugnisses nach § 28 Abs. 1 Satz 3 BauGB"],
    ["019", "Erteilung des Zeugnisses nach § 22 Abs. 5 BauGB"],
    ["020", "Erteilung des Zeugnisses nach § 145 Abs. 6 BauGB"],
    ["021", "Erteilung des Zeugnisses nach § 5 GrdstVG und hilfsweise der Genehmigung nach § 2 GrdstVG"],
    ["022", "Erteilung des Zeugnisses nach § 6 Abs. 3 GrdstVG"],
    ["023", "Erteilung der Bescheinigung nach § 11 Abs. 2 GrdstVG"],
    ["024", "Erteilung der Genehmigung nach § 3 ASVG"],
    ["025", "Erteilung des Zeugnisses nach § 5 ASVG und hilfsweise der Genehmigung nach § 3 ASVG"],
    ["026", "Erteilung des Zeugnisses nach § 28 Abs. 4 ASVG"],
    ["027", "Erteilung der Bescheinigung nach § 9 Abs. 2 ASVG"],
    ["028", "Erteilung der landwirtschaftsgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte und hilfsweise um Erteilung eines Negativattests"]
   ]
  },
  "vollstaendig": true,
  "quelle": "Genericode (XRepository): ENOVA.ErsuchenSachentscheidung-1.0.xml, ENOVA.ErsuchenSachentscheidung-1.1.xml"
 },
 "enova.sachentscheidung": {
  "name": "ENOVA.Sachentscheidung",
  "uri": "urn:xoev-de:xjustiz:codeliste:enova.sachentscheidung",
  "typ": 3,
  "standardVersion": "1.0",
  "versionen": {
   "1.0": [
    ["001", "Es besteht kein gesetzliches Vorkaufsrecht der Gemeinde an dem Grundbesitz."],
    ["002", "Es besteht ein gesetzliches Vorkaufsrecht der Gemeinde an dem Grundbesitz. Um Übermittlung einer Abschrift des Kaufvertrags wird gebeten."],
    ["003", "Auf die Ausübung des/der gesetzlichen Vorkaufsrechts/-e der Gemeinde wird verzichtet."],
    ["004", "Mitteilung über die Ausübung des Vorkaufsrechts"],
    ["005", "Erteilung Genehmigung gemäß §§ 144, 145 BauGB"],
    ["006", "Es bedarf keiner Genehmigung gemäß §§ 144, 145 BauGB"],
    ["007", "Erteilung der Genehmigung gemäß § 169 Abs. 1 Nr. 3 i.V.m. §§ 144, 145 BauGB"],
    ["008", "Es bedarf keine Genehmigung gemäß § 169 Abs. 1 Nr. 3 i.V.m. §§ 144, 145 BauGB"],
    ["009", "Erteilung der Genehmigung gemäß § 22 BauGB"],
    ["010", "Es bedarf keiner Genehmigung gemäß § 22 BauGB"],
    ["011", "Erteilung der Genehmigung gemäß §§ 172, 173 BauGB"],
    ["012", "Es bedarf keiner Genehmigung gemäß §§ 172, 173 BauGB"],
    ["013", "Erteilung der Genehmigung gemäß § 51 BauGB"],
    ["014", "Es bedarf keiner Genehmigung gemäß § 51 BauGB"],
    ["015", "Erteilung der Genehmigung gemäß §§ 108, 109 BauGB"],
    ["016", "Es bedarf keiner Genehmigung gemäß §§ 108, 109 BauGB"],
    ["017", "Erteilung der Genehmigung gemäß § 250 BauGB"],
    ["018", "Es bedarf keiner Genehmigung gemäß § 250 BauGB"],
    ["019", "Erteilung der Genehmigung gemäß § 2 GrdstVG"],
    ["020", "Es bedarf keiner Genehmigung gemäß § 2 GrdstVG"],
    ["021", "Erteilung der Genehmigung gemäß § 2 GVO"],
    ["022", "Es bedarf keiner Genehmigung gemäß § 2 GVO"],
    ["023", "Erteilung der familiengerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte"],
    ["024", "Die Urkunde bedarf keiner familiengerichtlichen Genehmigung."],
    ["025", "Erteilung der betreuungsgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte"],
    ["026", "Die Urkunde bedarf keiner betreuungsgerichtlichen Genehmigung."],
    ["027", "Erteilung der nachlassgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte"],
    ["028", "Die Urkunde bedarf keiner nachlassgerichtlichen Genehmigung."],
    ["029", "Erteilung eines Rechtskraftzeugnisses gemäß § 46 FamFG."],
    ["030", "Erteilung der Unbedenklichkeitsbescheinigung gemäß § 22 GrEStG"],
    ["031", "Mitteilung über die Ablehnung des Antrags"]
   ],
   "1.1": [
    ["001", "Es besteht kein gesetzliches Vorkaufsrecht gemäß §§ 24 ff. BauGB der Gemeinde an dem Grundbesitz."],
    ["002", "Es besteht ein gesetzliches Vorkaufsrecht der Gemeinde gemäß §§ 24 ff. BauGB an dem Grundbesitz. Um Übermittlung einer Abschrift des Kaufvertrags wird gebeten."],
    ["003", "Auf die Ausübung des/der gesetzlichen Vorkaufsrechts/-e gemäß §§ 24 ff. BauGB der Gemeinde wird verzichtet."],
    ["004", "Mitteilung über Vorkaufsrechtsausübung gemäß §§ 24 ff. BauGB"],
    ["005", "Erteilung Genehmigung gemäß §§ 144, 145 BauGB"],
    ["006", "Es bedarf keiner Genehmigung gemäß §§ 144, 145 BauGB"],
    ["007", "Erteilung der Genehmigung gemäß § 169 Abs. 1 Nr. 3 i.V.m. §§ 144, 145 BauGB"],
    ["008", "Es bedarf keine Genehmigung gemäß § 169 Abs. 1 Nr. 3 i.V.m. §§ 144, 145 BauGB"],
    ["009", "Erteilung der Genehmigung gemäß § 22 BauGB"],
    ["010", "Es bedarf keiner Genehmigung gemäß § 22 BauGB"],
    ["011", "Erteilung der Genehmigung gemäß §§ 172, 173 BauGB"],
    ["012", "Es bedarf keiner Genehmigung gemäß §§ 172, 173 BauGB"],
    ["013", "Erteilung der Genehmigung gemäß § 51 BauGB"],
    ["014", "Es bedarf keiner Genehmigung gemäß § 51 BauGB"],
    ["015", "Erteilung der Genehmigung gemäß §§ 108, 109 BauGB"],
    ["016", "Es bedarf keiner Genehmigung gemäß §§ 108, 109 BauGB"],
    ["017", "Erteilung der Genehmigung gemäß § 250 BauGB"],
    ["018", "Es bedarf keiner Genehmigung gemäß § 250 BauGB"],
    ["019", "Erteilung der Genehmigung gemäß § 2 GrdstVG"],
    ["020", "Es bedarf keiner Genehmigung gemäß § 2 GrdstVG (Zeugnis § 5 GrdstVG)"],
    ["021", "Erteilung der Genehmigung gemäß § 2 GVO"],
    ["022", "Es bedarf keiner Genehmigung gemäß § 2 GVO"],
    ["023", "Erteilung der familiengerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte"],
    ["024", "Die Urkunde bedarf keiner familiengerichtlichen Genehmigung."],
    ["025", "Erteilung der betreuungsgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte"],
    ["026", "Die Urkunde bedarf keiner betreuungsgerichtlichen Genehmigung."],
    ["027", "Erteilung der nachlassgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte"],
    ["028", "Die Urkunde bedarf keiner nachlassgerichtlichen Genehmigung."],
    ["029", "Erteilung eines Rechtskraftzeugnisses gemäß § 46 FamFG."],
    ["030", "Erteilung der Unbedenklichkeitsbescheinigung gemäß § 22 GrEStG"],
    ["031", "Mitteilung über die Ablehnung des Antrags"],
    ["032", "Erteilung der Genehmigung unter Bedingungen / Auflagen / Befristung"],
    ["033", "Um Übermittlung einer Urkundsabschrift wird gebeten."],
    ["034", "Erteilung des Zeugnisses gemäß § 22 Abs. 5 BauGB"],
    ["035", "Erteilung des Zeugnisses gemäß § 145 Abs. 6 BauGB"],
    ["036", "Erteilung des Zeugnisses gemäß § 6 Abs. 3 GrdstVG"],
    ["037", "Erteilung der Bescheinigung gemäß § 11 Abs. 2 GrdstVG"],
    ["038", "Erteilung der Genehmigung gemäß § 3 ASVG"],
    ["039", "Es bedarf keiner Genehmigung gemäß § 3 ASVG (Zeugnis § 5 ASVG)."],
    ["040", "Erteilung des Zeugnisses gemäß § 28 Abs. 4 ASVG"],
    ["041", "Erteilung der Bescheinigung gemäß § 9 Abs. 2 ASVG"],
    ["042", "Erteilung der landwirtschaftsgerichtlichen Genehmigung für sämtliche in der Urkunde enthaltenen genehmigungsbedürftigen Rechtsgeschäfte"],
    ["043", "Die Urkunde bedarf keiner landwirtschaftsgerichtlichen Genehmigung."]
   ]
  },
  "vollstaendig": true,
  "quelle": "Genericode (XRepository): ENOVA.Sachentscheidung-1.0.xml, ENOVA.Sachentscheidung-1.1.xml"
 },
 "gds.bundesland": {
  "name": "Bundesland (Destatis)",
  "uri": "urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:bundesland",
  "typ": 3,
  "standardVersion": "2010-04-01",
  "versionen": {
   "2010-04-01": [
    ["01", "Schleswig-Holstein"],
    ["02", "Hamburg"],
    ["03", "Niedersachsen"],
    ["04", "Bremen"],
    ["05", "Nordrhein-Westfalen"],
    ["06", "Hessen"],
    ["07", "Rheinland-Pfalz"],
    ["08", "Baden-Württemberg"],
    ["09", "Bayern"],
    ["10", "Saarland"],
    ["11", "Berlin"],
    ["12", "Brandenburg"],
    ["13", "Mecklenburg-Vorpommern"],
    ["14", "Sachsen"],
    ["15", "Sachsen-Anhalt"],
    ["16", "Thüringen"]
   ]
  },
  "vollstaendig": true,
  "quelle": "vollständig"
 },
 "enova.grundstuecksart": {
  "name": "ENOVA.Grundstuecksart",
  "uri": "urn:xoev-de:xjustiz:codeliste:enova.grundstuecksart",
  "typ": 3,
  "standardVersion": "1.1",
  "versionen": {
   "1.1": [
    ["002", "Bebaut"],
    ["003", "Wohngebäude"]
   ]
  },
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "enova.artdesrechtsgeschaefts": {
  "name": "ENOVA.ArtDesRechtsgeschaefts",
  "uri": "urn:xoev-de:xjustiz:codeliste:enova.artdesrechtsgeschaefts",
  "typ": 3,
  "standardVersion": "",
  "versionen": {},
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "enova.gegenleistung": {
  "name": "ENOVA.Gegenleistung",
  "uri": "urn:xoev-de:xjustiz:codeliste:enova.gegenleistung",
  "typ": 3,
  "standardVersion": "",
  "versionen": {},
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "enova.grundderuebersendung": {
  "name": "ENOVA.GrundDerUebersendung",
  "uri": "urn:xoev-de:xjustiz:codeliste:enova.grundderuebersendung",
  "typ": 3,
  "standardVersion": "",
  "versionen": {},
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "enova.gueterstand": {
  "name": "ENOVA.Gueterstand",
  "uri": "urn:xoev-de:xjustiz:codeliste:enova.gueterstand",
  "typ": 3,
  "standardVersion": "",
  "versionen": {},
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "gds.dokumentklasse": {
  "name": "GDS.Dokumentklasse",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.dokumentklasse",
  "typ": 3,
  "standardVersion": "1.3",
  "versionen": {
   "1.3": [
    ["015", "Schreiben"]
   ]
  },
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "gds.dokumenttyp": {
  "name": "GDS.Dokumenttyp",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.dokumenttyp",
  "typ": 3,
  "standardVersion": "4.1",
  "versionen": {
   "4.1": [
    ["102", "Erwerbsurkunde"]
   ]
  },
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "gds.staaten": {
  "name": "BfJ.Staat",
  "uri": "urn:xoev-de:bund:bfj:codeliste:bfj.staat",
  "typ": 3,
  "standardVersion": "6.1",
  "versionen": {
   "6.1": [
    ["000", "Deutschland"],
    ["151", "Österreich"]
   ],
   "7.0": [
    ["000", "Deutschland"]
   ]
  },
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "gds.waehrung": {
  "name": "XKfz.Waehrung",
  "uri": "urn:xoev-de:bund:kba:codeliste:waehrung",
  "typ": 3,
  "standardVersion": "1.0",
  "versionen": {
   "1.0": [
    ["EUR", "Euro"]
   ]
  },
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "gds.gerichte": {
  "name": "GDS.Gerichte",
  "uri": "urn:xoev-de:xjustiz:codeliste:gds.gerichte",
  "typ": 3,
  "standardVersion": "3.6",
  "versionen": {
   "3.6": [
    ["D2601", "Amtsgericht München"]
   ]
  },
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 },
 "gds.finanzbehoerden": {
  "name": "GDS.Finanzbehoerden",
  "uri": "urn:xoev-de:ag-it-standards:codeliste:gds.finanzbehoerden",
  "typ": 3,
  "standardVersion": "",
  "versionen": {},
  "vollstaendig": false,
  "quelle": "Teilliste – offizielle Genericode-Datei aus dem XRepository importierbar"
 }
};
